name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Compile roman_to_arabic
      run: |
        gcc -Wall -Werror -Wextra -std=c11 -o ./src/roman_to_arabic ./src/roman_to_arabic.c

    - name: Install dependencies
      run: |
        pip install -r tests/requirements.txt

    - name: Run Pytest
      run: |
        pytest --color=yes -v --tb=short --html=pytest_report.html tests

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results
        path: pytest_report.html

    - name: Check code formatting
      run: |
        if [ -n "$(clang-format -output-replacements-xml -style=./clang/.clang-format $(find src -name '*.c' -o -name '*.h'))" ]; then
          echo "Code formatting issues found. Please run clang-format to fix them."
          exit 1
        fi